#===============================================================================
#
#  Description: Makefile the for event-based-library
#
#===============================================================================

#-------------  name of the target  --------------------------------------------
TARGET          = sapin2_api.a

# ------------  standard defines  ----------------------------------------------
PREDEFS         = 

#-------------  directory of the target  ---------------------------------------
TARGET_DIR      = ./lib

#-------------  directory of source files --------------------------------------
SOURCE_DIR      = ./

# ------------  additional include directories  --------------------------------
INC_DIR         = ../include

include ../spinn2_common.mk

